# Generated by Django 5.0.2 on 2024-04-16 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_category_flashcards_category_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flashcards',
            name='domain',
        ),
    ]
