# Generated by Django 5.0.2 on 2024-04-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_remove_flashcards_category_remove_flashcards_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.category'),
        ),
        migrations.AddField(
            model_name='flashcards',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.domain'),
        ),
    ]
