# Generated by Django 5.0.2 on 2024-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcards_category_flashcards_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
