# Generated by Django 5.0.2 on 2024-04-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_flashcards_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcards',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flashcards',
            name='domain',
        ),
        migrations.CreateModel(
            name='CategoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcards')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.category')),
            ],
        ),
        migrations.AddField(
            model_name='flashcards',
            name='category_cards',
            field=models.ManyToManyField(through='flashcards.CategoryCard', to='flashcards.category'),
        ),
        migrations.CreateModel(
            name='DomainCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcards')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.domain')),
            ],
        ),
        migrations.AddField(
            model_name='flashcards',
            name='domain_cards',
            field=models.ManyToManyField(through='flashcards.DomainCards', to='flashcards.domain'),
        ),
    ]
